input {
  tcp {
    port => 5000
    codec => json
  }
}

filter {
  mutate {
    add_field => { "application" => "roadguard-ai" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "roadguard-logs-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
